# -*- coding: utf-8 -*-
"""simple_first_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NfQGEJoZgz0fj5Si6xOhFpLWJbCjcZA
"""

!pip install google-generativeai --quiet
!pip install ipywidgets --quiet

import google.generativeai as genai
import ipywidgets as widgets
from IPython.display import display,Markdown

Api_key  = "YOUR_API_KEY"
genai.configure(api_key=Api_key)
model = genai.GenerativeModel("gemini-2.5-flash")

import ipywidgets as widgets

topic_input = widgets.Text(
    description="Topic",
    layout=widgets.Layout(width='500px')
)
tone_input = widgets.Dropdown(
    description="Tone",
    options=["Professional", "Casual", "Techy-way", "Motivational"],
    layout=widgets.Layout(width='500px')
)
audience_input = widgets.Text(
    description="Audience",
    layout=widgets.Layout(width='500px')
)
hashtag_input = widgets.Text(
    description="Hashtags",
    layout=widgets.Layout(width='500px')
)
button_input = widgets.Button(
    description="Generate_Tweet",
    button_style='success',
    tooltip="Click to generate tweet",
    layout=widgets.Layout(width='500px')
)
output = widgets.Output()

def generate_tweet(b):
    output.clear_output()

    prompt = f"""
You are an expert Content Writer.
Generate a tweet about the topic: "{topic_input.value}".
Use a tone: {description_input.value}.
Generate the tweet for audience: {audience_input.value}.
Include the hashtags: {hashtag_input.value}.
Keep it under 280 characters.
"""
    with output:
        try:
            response = model.generate_content(prompt)
            tweet = response.text.strip()
            display(Markdown(f"### Generated Tweet: \n\n{tweet}"))
        except Exception as e:
            print("Error:", e)
button_input.on_click(generate_tweet)

form = widgets.VBox([
    widgets.HTML(value="<h3>🧠 Tweet Generator Agent</h3>"),
    topic_input,
    tone_input,
    audience_input,
    hashtag_input,
    button_input,
    output
])

display(form)

